/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkspaceRequestsRouteImport } from './routes/workspace.requests'
import { Route as WorkspaceCommitteeRouteImport } from './routes/workspace.committee'
import { Route as WorkspaceCommandRouteImport } from './routes/workspace.command'
import { Route as WorkspaceAutomationsRouteImport } from './routes/workspace.automations'
import { Route as WorkspaceAuditRouteImport } from './routes/workspace.audit'
import { Route as WorkspaceAgentsRouteImport } from './routes/workspace.agents'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceRequestsRoute = WorkspaceRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCommitteeRoute = WorkspaceCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCommandRoute = WorkspaceCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAutomationsRoute = WorkspaceAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAuditRoute = WorkspaceAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAgentsRoute = WorkspaceAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/agents': typeof WorkspaceAgentsRoute
  '/workspace/audit': typeof WorkspaceAuditRoute
  '/workspace/automations': typeof WorkspaceAutomationsRoute
  '/workspace/command': typeof WorkspaceCommandRoute
  '/workspace/committee': typeof WorkspaceCommitteeRoute
  '/workspace/requests': typeof WorkspaceRequestsRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/workspace/agents': typeof WorkspaceAgentsRoute
  '/workspace/audit': typeof WorkspaceAuditRoute
  '/workspace/automations': typeof WorkspaceAutomationsRoute
  '/workspace/command': typeof WorkspaceCommandRoute
  '/workspace/committee': typeof WorkspaceCommitteeRoute
  '/workspace/requests': typeof WorkspaceRequestsRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/agents': typeof WorkspaceAgentsRoute
  '/workspace/audit': typeof WorkspaceAuditRoute
  '/workspace/automations': typeof WorkspaceAutomationsRoute
  '/workspace/command': typeof WorkspaceCommandRoute
  '/workspace/committee': typeof WorkspaceCommitteeRoute
  '/workspace/requests': typeof WorkspaceRequestsRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/workspace'
    | '/workspace/agents'
    | '/workspace/audit'
    | '/workspace/automations'
    | '/workspace/command'
    | '/workspace/committee'
    | '/workspace/requests'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal'
    | '/workspace/agents'
    | '/workspace/audit'
    | '/workspace/automations'
    | '/workspace/command'
    | '/workspace/committee'
    | '/workspace/requests'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/workspace'
    | '/workspace/agents'
    | '/workspace/audit'
    | '/workspace/automations'
    | '/workspace/command'
    | '/workspace/committee'
    | '/workspace/requests'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/requests': {
      id: '/workspace/requests'
      path: '/requests'
      fullPath: '/workspace/requests'
      preLoaderRoute: typeof WorkspaceRequestsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/committee': {
      id: '/workspace/committee'
      path: '/committee'
      fullPath: '/workspace/committee'
      preLoaderRoute: typeof WorkspaceCommitteeRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/command': {
      id: '/workspace/command'
      path: '/command'
      fullPath: '/workspace/command'
      preLoaderRoute: typeof WorkspaceCommandRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/automations': {
      id: '/workspace/automations'
      path: '/automations'
      fullPath: '/workspace/automations'
      preLoaderRoute: typeof WorkspaceAutomationsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/audit': {
      id: '/workspace/audit'
      path: '/audit'
      fullPath: '/workspace/audit'
      preLoaderRoute: typeof WorkspaceAuditRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/agents': {
      id: '/workspace/agents'
      path: '/agents'
      fullPath: '/workspace/agents'
      preLoaderRoute: typeof WorkspaceAgentsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceAgentsRoute: typeof WorkspaceAgentsRoute
  WorkspaceAuditRoute: typeof WorkspaceAuditRoute
  WorkspaceAutomationsRoute: typeof WorkspaceAutomationsRoute
  WorkspaceCommandRoute: typeof WorkspaceCommandRoute
  WorkspaceCommitteeRoute: typeof WorkspaceCommitteeRoute
  WorkspaceRequestsRoute: typeof WorkspaceRequestsRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAgentsRoute: WorkspaceAgentsRoute,
  WorkspaceAuditRoute: WorkspaceAuditRoute,
  WorkspaceAutomationsRoute: WorkspaceAutomationsRoute,
  WorkspaceCommandRoute: WorkspaceCommandRoute,
  WorkspaceCommitteeRoute: WorkspaceCommitteeRoute,
  WorkspaceRequestsRoute: WorkspaceRequestsRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
